### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/sergio_description#3]
CMake Error at sergio_description/CMakeLists.txt:23 (add_custom_target):
  add_custom_target cannot create target "media_files" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/rokus/ros/indigo/system/src/amigo_description".  See documentation
  for policy CMP0002 for more details.

**Comment by Timple** [comment]
Same here!
Op 12 aug. 2015 00:04 schreef "Rokus" <notifications@github.com>:

**Comment by reinzor** [comment]
Jaaaaah, zal het fixen als ik tijd heb. Simpele rename van de target.

**Comment by reinzor** [comment]
Goed bezig G!
